### ISSUE TITLE
Release models on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [gmongaras/Cottention_Transformer#4]
Hello @gmongaras 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through AK's daily papers: https://huggingface.co/papers/2409.18747. The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the models you've pre-trained on https://huggingface.co/models, rather than Google Drive? Hosting on Hugging Face will give you more visibility. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

## Uploading models

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

What do you think?

Kind regards,

Niels

**Comment by gmongaras** [comment]
Thanks for letting us know! Added the models to a HF collection:
https://huggingface.co/collections/gmongaras/cosine-attention-cottention-6703e482a3f9131cd2d6ee89

**Comment by NielsRogge** [comment]
Thanks a lot! Collection looks great :) 

I've opened a PR to link the models to the paper page: https://huggingface.co/gmongaras/Cosine_Attention_GPT_300M/discussions/1. Would be great to update the other ones too :)
